<?php
    if (empty($this->currentProduct)) {
        $this->autoRefresh = true;
        $this->changeProduct = true;
    } elseif ($this->currentProduct['id'] == $this->productData['id']) {
        $this->autoRefresh = true;
    }
    $this->headLink()->appendStylesheet('/css/colorbox.css');
    $this->headScript()->appendFile('/js/jquery-1.7.2.min.js', 'text/javascript');
    $this->headScript()->appendFile('/js/jquery.colorbox-min.js', 'text/javascript');
    $this->headScript()->appendScript("
        $(function() {
            $('#image a').colorbox({rel: 'productImages'});
        });
    ");
    if ($this->autoRefresh) {
        $this->headScript()->appendFile($this->socketServer . '/socket.io/socket.io.js', 'text/javascript');
        $this->headScript()->appendScript('var site = "' . $this->site . '"; var socketServer = "' . $this->socketServer
            . '"; var changeProduct = ' . (($this->changeProduct) ? 'true' : 'false') . ';');
        $this->headScript()->appendFile('/js/product-update.js', 'text/javascript');
    }
?>
<div id="product-container">
    <div id="image">
        <a href="/images/products/<?php echo $this->productData['id'] ?><?php echo $this->productData['file_extension']; ?>">
            <img alt="<?php echo str_replace('"','&quote;',$this->productData['title']); ?>" src="/images/products/<?php echo $this->productData['id'] ?><?php echo $this->productData['file_extension']; ?>" />
        </a>
        <a id="detailImage" href="/images/products/<?php echo $this->productData['id'] ?>_detail<?php echo $this->productData['file_extension']; ?>">
            <img alt="<?php echo str_replace('"','&quote;',$this->productData['title']); ?>" src="/images/products/<?php echo $this->productData['id'] ?>_detail<?php echo $this->productData['file_extension']; ?>" />
        </a>
    </div>
    <div id="product-info">
        <div id="title">
            <?php echo $this->productData['title']; ?>
            <a href="<?php echo $this->productData['link'];?>" target="_blank" id="permalink">(permalink)</a>
        </div>
        <div id="price">
            $<?php echo $this->productData['price']; ?>
        </div>
        <div id="shipping">
            + $<?php echo $this->productData['shipping']; ?> shipping
        </div>
        <div id="condition">
            <dl>
                <dt>Condition:</dt>
                <dd>
                    <?php echo $this->productData['condition']; ?>
                </dd>
            </dl>
        </div>
        <div id="product">
            <dl>
                <dt>Product:</dt>
                    <?php foreach($this->productData['products'] as $product): ?>
                    <dd>
                        <?php echo $product['quantity']; ?> <?php echo $product['name']; ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
            <div class="clearfix"></div>
        </div>

        <?php $current = end($this->productData['history']); ?>
        <?php if(empty($this->currentProduct) || $this->productData['id'] == $this->currentProduct['id']): ?>
        <div id="buy-link">
                <?php if(!$current['sold_out'] && $current['percent_sold'] < .9): ?>
                    <a href="<?php echo $this->productData['purchase_url']; ?>">I want one!</a>
                <?php elseif(!$current['sold_out'] && $current['percent_sold'] >= .9): ?>
                    <a href="<?php echo $this->productData['purchase_url']; ?>">I want one!<br />(They're almost gone!)</a>
                <?php else: ?>
                    Sold out!
                <?php endif; ?>
            </div>
        <?php endif; ?>

        <div id="comment-container">
            <a href="<?php echo $this->productData['thread']; ?>" target="_blank"><?php echo $current['comments']; ?> comment<?php echo (($current['comments'] == 0 || $current['comments'] > 1) ? 's' : '');?></a>
        </div>
    </div>
    <?php
    if ($this->productData['wootoff'] && empty($this->currentProduct)):
        $percentLeft = (1-$this->productData['history'][0]['percent_sold'])*100;
    ?>
    <div id="woot-off">
        Woot!-off
        <div id="progress-bar">
            <span id="progress-percent"><?php echo $percentLeft ?>%</span>
            <div id="progress-bar-inner" style="width: <?php echo $percentLeft; ?>%"></div>
        </div>
    </div>
    &nbsp;
    <?php endif;?>
    <div id="time-updated"></div>
    <div class="clearfix">
        <div class="triangle"></div>
    </div>
</div>
<?php $this->placeholder('secondary')->set(
          '<div id="subtitle">'.
          str_replace("'",'&apos;',$this->productData["subtitle"]) .
          '</div>
        <div id="teaser">' .
          str_replace("'", '&apos;', $this->productData["teaser"]) .
          '</div>'
    );