<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Darkstar's Woot-off Checker v3</title>
  <?php $this->headLink()->appendStylesheet('/css/common.css') ?>
  <?php $this->headLink()->appendStylesheet('/css/'.$this->site.'.css') ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->headScript(); ?>
</head>
<body>
    <div id="main-wrapper">
        <div id="logo">DSwoot/<?php echo ucfirst($this->site); ?></div>
        <?php echo $this->layout()->content; ?>
        <div class="clearfix"></div>
    </div>
    <div class="rounded-wrapper">
        <?php echo $this->placeholder('secondary'); ?>
    </div>
</body>
</html>
